print("name: James")
print("jumpforce: 20")
print("special power: Infinite nitro")
print("speed: 320")
print("car: Honda Civic type R")
print("lives left: just: 3")
print("ammo: 121")
print("number of lasers: 4")
print("battery power: 90")
print("level: 90")
print("wanted: True")
